### ISSUE TITLE
Matching Python kernels and order

### ISSUE THREAD

**Issue by damianavila** [Anaconda-Platform/nb_conda_kernels#11]
Ref: https://github.com/ContinuumIO/wakari-app-ipython/issues/54

**Comment by ijstokes** [comment]
I think the discussion about https://github.com/ContinuumIO/wakari-app-ipython/issues/54 really belongs here, since this is where any changes will happen.  @damianavila added these comments in FD:

> I don't think it is a bug... it is an intended behavior, your kernels ARE associated with a specific environment where you know you have all the dependencies to run it successfully. If you pass the notebook to a colleague, you need to provide it the environment specification (which includes the name), then the recipient re-creates the environment from the specification and when they try to open the notebook they start the kernel successfully. Otherwise, the warning is shown and the user can decide to run the notebook in another environment that could (or not) satisfy all the dependencies and run (or not) successfully.
We can probably discuss further what happens if two users have the same name environment... in that case, the probably need to make the name unique somehow...

I agree *in general*, however the novice user will be confused by this, IMO.  I feel like for "standard" kernels such as "Python" or "R", we should consider if it is possible to make a suggestion or automatically connect to an existing kernel in the current environment (or perhaps from another accessible environment).

**Comment by mcg1969** [comment]
@damianavila do you think this issue is still relevant; and if so, what would be the path forward?

**Comment by mcg1969** [comment]
OK, sounds good
