### ISSUE TITLE
nb_conda_kernels and jupyter notebook extensions

### ISSUE THREAD

**Issue by skwde** [Anaconda-Platform/nb_conda_kernels#206]
When using extensions, dependencies (to my knowledge) have to be installed into each kernel environment separately.

A typical example would be the jupyter extension Autopep8 requries the package `autopep8`.
Currently I have to install `autopep8` in every kernel environment.

Is there a way to only install such extension dependencies to the actual notebook enviornment and not to every kernel environment I want to use in a notebook?

**Comment by tbsexton** [comment]
@skwde I actually started using nb_conda_kernels _specifically_ to avoid this isssue: 

For instance, in my `base` or a dedicated `notebook` environment (uses `-c conda-forge` iirc): 
- `nb_conda_kernels`
- `jupytext`
- `jupyter_contrib_nbextensions`
- `rise`

This is the environment that the server runs in: `~$ jupyter notebook`

Then in every kernel environment, as long as I install a kernel to it (e.g. `ipykernel`), I will get an option in my notebooks to use the that environment directly. Since all the extensions/tools/etc are in the environment running the notebook server, I can use them at any time, in any of the kernels.

**Comment by skwde** [comment]
@tbsexton As I see it, it is not necessarily true that 
> all the extensions/tools/etc are in the environment running the notebook server, I can use them at any time, in any of the kernels

If I for example use the jupyter extension `jupyter-autopep8` installed on the server, I still have to install `autopep8` into each environment to use the extension. 
That is actually the point I tried to make in the first place.

**Comment by fcollonval** [comment]
@skwde the all points of using environment is to separate installed packages set.

:warning: So to succeed at sharing packages between environments, you can configure your `PYTHONPATH` to point to directories that store shared packages. I want to insist that by doing so, you will break the isolation of environments.

**Comment by skwde** [comment]
@tbsexton I agree that `environment.yml` are great to keep track of environments and also share them.

However I still don't think that packages, installed because they are jupyter extension dependencies such as `autopep8`, should be in the `ipykernel` environment. They should stay with the extension.
Otherwise it simply leads to duplicated installes.

Also your point regarding interoperability does not realy hold in my opinion. Just image the person I am sharing the enviornment with doesn't use the same jupyter extensions. Worse still, if the person doesn't even use jupyter than he gets an environment with not only `ipykernel` as a useless package but also numerous others.

**Comment by fcollonval** [comment]
The discussion is getting quite of topic.

To sum-up, the requirement of `autopep8` on each environment is a consequence of the implementation in [`jupyter-autopep8`](https://github.com/kenkoooo/jupyter-autopep8). @skwde you could open a request on that repository to use the library installed in the server environment rather than in the kernel environment.

If you need to share packages between environment, I suggest (but this can be dangerous) to make use of `PYTHONPATH`.

> A small comment, I don't know the rational behind the need of autopep8 requirement to be in the kernel environment. But I can image it has do with supporting various versions of Python.
