### ISSUE TITLE
New installation procedure for Anaconda 4.1

### ISSUE THREAD

**Issue by pylang** [Anaconda-Platform/nb_conda_kernels#32]
Since this package is not included in the latest version of Anaconda, how do you install it?  The README instructions seem applicable to cloned repos only.

I assumed I could make a conda environment, open a notebook and find the env's python kernel listed in the notebook/dashboard dropdown menu, but that is not the case.  What must be done to initiate this behavior?  

Many thanks.

**Comment by pylang** [comment]
It does seem that making an env from an environment.yaml file auto installs a kernelspec.  Assuming a python version is detailed in your yaml file, the README instructions would change to something like this:

```
# environment_example.yaml
name: envname
dependencies:
- python=3.5.1=4
- ...                                 # other dependencies
```

```
> conda env update -f environment_example.yaml
> activate envname                    # optional
> jupyter notebook
```

A new environment called "envname" is created and can be activated if desired.  Additionally, a new kernel called "envname" is now added to the dropdown menu in the dashboard, which is accessed by initiating the notebook in any environment.

**Comment by damianavila** [comment]
We need to explain better, you are right...

>You can initiate the jupyter notebook command from your native environment. You don't have to be inside a conda enviroment to generate a kernelspec.

That's correct, kernelspecs are generated on the fly for any of your environments having a ipykernel available...

> notebook is required to in the yaml to generate the kernelspec.

In fact, you only need the `ipykernel` package in the environment... since the `notebook` also install the `ipykernel` package you saw the notebook as a requirement...

>conda env remove -n envname also removes the kernelspec, as desired.

Technically, there is no installation or deltion of kernelspec... there are created on the fly and removed when the target enviroment is no longer there...

Hope this helps to understand the extension a little bit more...

**Comment by pylang** [comment]
Thanks @damianavila.  Always appreciate your work as I use it the most :)

**Comment by damianavila** [comment]
We need a note in the docs: https://docs.continuum.io/anaconda/jupyter-notebook-extensions, about the need of `ipykernel` in the environment you want to have a kernelspec pointing at...

**Comment by mcg1969** [comment]
I believe we're in good shape here. I've cleaned up the docs and I do talk about making sure the kernels are installed properly.
