### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by meganmetzger** [Anaconda-Platform/nb_conda_kernels#62]
Hi,

I'm having an issue where when I launch jupyter notebook, it gives me a Kernel Error. I have tried using anaconda, and also uninstalling anaconda and running from the base python with the same results. I have no clue what's going on. I have read the similar responses here, but nothing there has seemed to work. Any thoughts on what I can do?

The error looks like this:

 File "/Users/meganicka/anaconda/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Presumably it's looking for python in the wrong place, but I don't know how to get it to look in the correct place.

Thanks in advance for your help.

Best,

Megan

**Comment by damianavila** [comment]
Is using the default Anaconda failing as well? Can you post the complete stack trace? Any other particular things in your deploy you believe could help to know what is happening?

**Comment by damianavila** [comment]
Closing as stale, please re-open if you have more information. Cheers.

**Comment by BrenBarn** [comment]
I am getting a similar error.  If I go to the "Conda" tab in the notebook, I get two popups saying "An error occurred while listing Conda environments." and "An error occurred while retrieving package information."  Each also says "Internal server error".  In the console where I launched the notebook, this stack trace appears:

```
[E 13:50:02.409 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\FakeProgs\Anaconda3\envs\nb_conda_kernels\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\FakeProgs\Anaconda3\envs\nb_conda_kernels\lib\site-packages\nb_conda\handlers.py", line 229, in get
        data = searcher.list_available(self)
      File "C:\FakeProgs\Anaconda3\envs\nb_conda_kernels\lib\site-packages\nb_conda\handlers.py", line 213, in list_available
        bufsize=4096)
      File "C:\FakeProgs\Anaconda3\envs\nb_conda_kernels\lib\subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "C:\FakeProgs\Anaconda3\envs\nb_conda_kernels\lib\subprocess.py", line 955, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by damianavila** [comment]
This seems to be an issue with nb_conda, not nb_conda_kernels. I would try to reproduce it, but we should put it in the proper issue tracker.

Can you post your notebook, nb_conda_kernels and nb_conda versions? A `conda list` from your environment should be enough to get this info.

**Comment by BrenBarn** [comment]
The versions:

```
nb_conda                  2.0.0                    py35_0
nb_conda_kernels          2.0.0                    py35_0
notebook                  5.0.0                    py35_0
```

I think I have an idea what the problem is.  On Windows, the various Anaconda tools (like conda) in each environment are batch files that use the `call` shell command to call the main version in the root environment.  But since `call` is a shell command, it doesn't work unless you use `shell=True` in the various subprocess calls, which `nb_conda` is not doing.

I think the use of these subprocess calls also means it won't work if I try to start the notebook without activating its conda environment (since the path won't be set right), but I guess that's more of an overall issue with the conda architecture.

**Comment by damianavila** [comment]
> I think I have an idea what the problem is. On Windows, the various Anaconda tools (like conda) in each environment are batch files that use the call shell command to call the main version in the root environment. But since call is a shell command, it doesn't work unless you use shell=True in the various subprocess calls, which nb_conda is not doing.

I was suspecting the same... thanks for confirm it.

> I think the use of these subprocess calls also means it won't work if I try to start the notebook without activating its conda environment (since the path won't be set right), but I guess that's more of an overall issue with the conda architecture.

I am not sure about this, can you elaborate further? I need to understand better the example you are proposing.

**Comment by BrenBarn** [comment]
Maybe I am wrong.  My thinking is that something like `subprocess.call(['conda', 'info'])` will do whatever `conda info` means in the current environment.  I guess this will be okay as long as all that's being done is stuff like `conda info` (which in theory should be consistent across all environments).

What won't work is trying to use the nb_conda_env tab from a notebook that's started when no conda environment at all is active (since then `conda` won't be on the path at all).  But maybe that is reasonable, since after all the name of the package is `nb_conda_kernels` so it's not outrageous that it wouldn't run if your notebook isn't running in a conda environment.

**Comment by damianavila** [comment]
> What won't work is trying to use the nb_conda_env tab from a notebook that's started when no conda environment at all is active (since then conda won't be on the path at all). But maybe that is reasonable, since after all the name of the package is nb_conda_kernels so it's not outrageous that it wouldn't run if your notebook isn't running in a conda environment.

Yep, if you don't have conda installed things will fail... if it is installed, the executable lives in the root environment and it is accessible from every new env you create, then it will not fail (even if you don't have conda installed in the new environment, because, in fact, you can not install conda in new environments).
