### ISSUE TITLE
Question: passing environment variables to kernel

### ISSUE THREAD

**Issue by fcollonval** [Anaconda-Platform/nb_conda_kernels#97]
The new behavior introduced by #80 implies the search for all environment variables to transfer them to the kernel (if I got it right).

But `conda info --json` command is also called in the kernel specification building process. And it provides with some (all?) environment variables throught the `env_vars` key. Could we take advantage of that and suppress the additional `subprocess` call?

**Comment by mcg1969** [comment]
No, the additional subprocess call cannot be avoided; they do different things. `conda info --json` is used to determine information about the root conda installation. The additional subprocess call is required in order to run the activate scripts when a kernel is selected. Activate scripts typically just set environment variables, but they are in theory allowed to do other things.
